context:
  version: "1.0.2"

recipe:
  name: ros-infra-variants
  version: ${{ version }}

source:
  - url: "https://github.com/ros-infrastructure/infra-variants/archive/refs/tags/${{ version }}.tar.gz"
    sha256: "a10a63af16a7d83c3fabbd089eac8f9b951406cfbcf3e8ced1979cc3c8234a07"

build:
  number: 0
  noarch: generic

outputs:
  - package:
      name: ros-build-essential
    requirements:
      run:
        - cxx-compiler
        - make
        - cmake
        - git
        - python
        - setuptools
        - pkg-config
        - ninja
    tests:
      - script:
          - echo "This is a meta-package, no test is necessary."
  - package:
      name: ros-dev-tools
    requirements:
      run:
        - ros-build-essential
        - colcon-common-extensions
        - colcon-mixin
        - rosdep
        - vcstool
    tests:
      - script:
          - echo "This is a meta-package, no test is necessary."

about:
  homepage: https://github.com/ros-infrastructure/infra-variants
  repository: https://github.com/ros-infrastructure/infra-variants
  license: "Apache-2.0"
  license_file: "LICENSE"
  summary: "ROS Infrastructure variant packages."

extra:
  feedstock-name: ros-infra-variants
  recipe-maintainers:
    - traversaro
