context:
  version: "1.0.3"

recipe:
  name: ros-infra-variants
  version: ${{ version }}

source:
  - url: "https://github.com/ros-infrastructure/infra-variants/archive/refs/tags/${{ version }}.tar.gz"
    sha256: "1c2a50e66da3c177b1b40f2eda9063657d357102e010cd60d311c31c2b39d6eb"

build:
  number: 0
  noarch: generic

outputs:
  - package:
      name: ros-build-essential
    requirements:
      run:
        - cxx-compiler
        - make
        - cmake
        - git
        - python
        - setuptools
        - pkg-config
        - ninja
    tests:
      - script:
          - echo "This is a meta-package, no test is necessary."
  - package:
      name: ros-dev-tools
    requirements:
      run:
        - ros-build-essential
        - colcon-common-extensions
        - colcon-mixin
        - rosdep
        - vcstool
    tests:
      - script:
          - echo "This is a meta-package, no test is necessary."

about:
  homepage: https://github.com/ros-infrastructure/infra-variants
  repository: https://github.com/ros-infrastructure/infra-variants
  license: "Apache-2.0"
  license_file: "LICENSE"
  summary: "ROS Infrastructure variant packages."

extra:
  feedstock-name: ros-infra-variants
  recipe-maintainers:
    - traversaro
